Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,7 @@ jobs:
 
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
+        id: check
         run: |
           echo "Listing Directories"
           ls -a
@@ -38,3 +39,14 @@ jobs:
           mvn --version
           gradle --version
           ant -version
+          continue-on-error: true
+      - name: Check on Success
+        if: steps.check.outcome == 'success'
+        run: echo "UnitTesting for the Build has been completed successfully"
+      - name: Check on Failure
+        if: steps.check.outcome == 'failure'
+        run: |
+          echo "UnitTesting for the Build has been failed"
+          exit 1
+    
+      
